# Generated by Django 5.0.1 on 2025-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rustdetectionresult',
            name='rust_detected',
        ),
        migrations.AddField(
            model_name='rustdetectionresult',
            name='rust_class',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
