# Generated by Django 5.0.1 on 2025-04-06 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_remove_rustdetectionresult_rust_detected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_images')),
                ('label', models.CharField(choices=[('common_rust', 'Common Rust'), ('healthy', 'Healthy'), ('other_disease', 'Other Disease')], max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
