# Generated by Django 5.2 on 2025-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_trainingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustdetectionresult',
            name='farmer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
